### ISSUE TITLE
interactive mode

### ISSUE THREAD

**Issue by cloudson** [cloudson/gitql#14]
An interactive mode similar to mysql could be cool ... 

``` bash
gitql -i
> select author from commits 
...
> select * from tags limit 3 
...

```

For this, we need something like [goline](https://github.com/nemith/goline)

**Comment by Code-Hex** [comment]
Please read [this](https://github.com/cloudson/gitql/pull/38)

**Comment by luizperes** [comment]
Shall we close this issue @cloudson? Once #38 is merged?

**Comment by cloudson** [comment]
Completely right @luizperes. I'm closing this as #46 was merged.
