### ISSUE TITLE
Usage of F* word in the demo video

### ISSUE THREAD

**Issue by mbabuskov** [cloudson/gitql#19]
I was about to show qitql to my 12-year old. Good thing I didn't. What's the point of that? The project seems very usable.

Thanks.

**Comment by rodorgas** [comment]
He will hear it sooner or later (probably had already).

**Comment by MikeBosw** [comment]
Ha love it

**Comment by caleblloyd** [comment]
It's a great teaching point. "that's what parents say under their breath when their code still doesn't work after an hour of debugging"

**Comment by r04r** [comment]
I'm sorry you feel that your child can't handle certain words. You should probably keep them off the internet entirely. Best to lock them in their room too, who knows what words they are exposed to outside.

**Comment by tp-robert-debowski** [comment]
Seriously? The use of the F* word in the presentation is higly unprofessional and violates the Open Code of Conduct.  This alone disqualifies this otherwise interesting project for any professional reviews. 

(and as a side note: comments regarding somebody's parental duties are just plain childish, but i guess that's just how the whole web rolls today.)

**Comment by sneak** [comment]
Fuck self-censorship.

**Comment by sneak** [comment]
The Open Code of Conduct is shit if it says you can't say `fuck`.

**Comment by MikeBosw** [comment]
Lol! As a New Yorker I'm always amazed at this particular prudishness

**Comment by sneak** [comment]
Just read the Open Code of Conduct, twice. Nowhere does it say `fuck` is banned.

**Comment by sneak** [comment]
Oh, they deleted their comments making that claim.

**Comment by nick-andren** [comment]
Could you clone and set up gitql locally, then delete the video? If you're going to show it off yourself, a real life demo would be great and may not need the video

**Comment by rileytg** [comment]
all you gotta do is fork it, delete the gif. it can all be on github.com

more importantly why would a 12 year old give a shit about this project? (no hate @cloudson, i'm a fan.) does she run your devops?

**Comment by rileytg** [comment]
"hey kid wanna see some gitql? just get in my van"

**Comment by cloudson** [comment]
@mbabuskov I was just trying to be funny. Sorry if I caused problems in your kid's education. 
I will work in a new video and recommend you to follow the tip until there

> Could you clone and set up gitql locally, then delete the video? ...

I will close this issue because it's more about education and lifestyle than this project.
