### ISSUE TITLE
Roadmap for release 1.0.0

### ISSUE THREAD

**Issue by cloudson** [cloudson/gitql#2]
* Management with alias 
```sql 
select * from commits c where c.hash = 'e69de2'
```
* Create functions 
   * NOW(), COUNT(), DATE_FORMAT()...

* `IS NULL` as possible right value

**Comment by cloudson** [comment]
Abandoned for now.

**Comment by jhonatanTeixeira** [comment]
You cant abandon this, bitch kkk

Em Qui, 6 de ago de 2015 19:37, Claudson Oliveira <notifications@github.com>
escreveu:

**Comment by cloudson** [comment]
LOL @jhonatanTeixeira .
Currently, i'm more interested in [features like that](https://github.com/cloudson/gitql/issues/18). 

But maybe we can reopen this issue soon. :smile:
