### ISSUE TITLE
Add COUNT(*)

### ISSUE THREAD

**Issue by angvp** [cloudson/gitql#26]
For instance for counting the number of commits of an Author ?

**Comment by cloudson** [comment]
It would to be an awesome feature for me. 
My main problem here is that I didn't find a way to do a count without a table scan. For big projects a query like 

` select count(*) from commits where "hell" in  message` 

will be very slow. Databases  use indexes to help on this work, maybe some strategy like that should to be used here. 
If you have some idea to do it with more performance, let me know @angvp .

**Comment by luizperes** [comment]
you could maybe create this feature for now @cloudson and improve the performance later... of course, telling people that this might be slow.

**Comment by angvp** [comment]
I do this with bash aliases, yes, it does full table scan, but git shortlog + wc it does pretty fast tho (in a repo of more than 2000~ commits)

**Comment by cloudson** [comment]
This is done, so closing the issue :D
