### ISSUE TITLE
JSON output?

### ISSUE THREAD

**Issue by KyleAMathews** [cloudson/gitql#27]
That'd make it useful for integrating with other tools.

**Comment by cloudson** [comment]
Hummm, interesting... if you want work on this @KyleAMathews , feel free. 
I would like to see that feature alive anyway :thinking:

**Comment by KyleAMathews** [comment]
I have a use case in mind for this but it'll be a while before I'd need it. Also my knowledge of Go is non-existent :-)

This is a cool effort though! Much more approachable interface to Git info vs. libgit2.

**Comment by luizperes** [comment]
Please check the PR https://github.com/cloudson/gitql/pull/34 @KyleAMathews and @cloudson . :)

**Comment by cloudson** [comment]
As the PR is merged, I am closing this.
