### ISSUE TITLE
rename the command git-ql to fit the standard extension design

### ISSUE THREAD

**Issue by ph-hs** [cloudson/gitql#29]
End users can then do:

$ git ql "etc"

**Comment by cloudson** [comment]
Hey @ph-hs 
When you do [make install](https://github.com/cloudson/gitql/blob/develop/Makefile#L26) , you have already a 'git ql' alias.

**Comment by ph-hs** [comment]
My bad, I was just watching the video

**Comment by cloudson** [comment]
No problem. 👍
