### ISSUE TITLE
Message wrong when using proxy tables

### ISSUE THREAD

**Issue by cloudson** [cloudson/gitql#3]
The tables "tags" and "branches" are something like _views_ from "refs", so 
1) Problem 1 

`select message from tags`

throws an error: table **'refs'** has not field 'message'.

 2) Problem 2
`select * from tags where type = 'blah'`

returns null instead of error, because table refs has the field type :confused:

**Comment by jsixface** [comment]
@cloudson Problem 1 seems to be fixed by b1f6f28
```
gitql> select message from tags
Error: Table 'tags' has not field 'message'
```
I'll look into Problem 2

**Comment by luizperes** [comment]
You're on fire!

**Comment by jsixface** [comment]
😄 I am learning Go and working on a open source project is a very good exercise.

**Comment by luizperes** [comment]
It is indeed! Keep the good work! :D
