### ISSUE TITLE
question: date query

### ISSUE THREAD

**Issue by vigo** [cloudson/gitql#33]
First of all, I really liked this tool. Thanks for it... Can you please give some more date query examples ? between dates for instance? I cross checked via git's:

    git log --online --since='4 months ago' --date=relative

and compared to `git sql`... It's like maximum 10 results for each query ?

**Comment by cloudson** [comment]
Hello @vigo 

Each date value can be represented with pattern `Y-m-d H:i:s`, for example:

```sql 
# commits since Dec 1st
select author, message, date from commits where date >= '2016-12-01 00:00:00'
```

```sql
# range: commits in november
gitql "select author, message, date from commits where date >= '2016-11-01 00:00:00' and date < '2016-12-01 00:00:00'
```

You can use the reserved word `limit` to define how many lines you can see. 
```sql
select author, message, date from commits where date >= '2016-11-01 00:00:00' and date < '2016-12-01 00:00:00' limit  20
```

If you think that our documentation could be better, we could work together to improve that. Let me know if want that.

**Comment by cloudson** [comment]
By the way. 
There is no way yet to define relative dates, but it would be a nice feature like [mysql date_add](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_date-add)

**Comment by vigo** [comment]
Thanks for answering... I had tried without `H:i:s` information. Now I understand the reason... One last thing, I guess the default limit value is 10... If I query like this:

```sql
select message,date from commits
```

I get 10 results... I think I need to set `limit` every time ?... Would be great if I can set a kind of env var something like `GITQL_DEFAULT_LIMIT=100` (just an idea) :)

**Comment by cloudson** [comment]
@vigo I tried 
```sql
select author, message, date from commits where date >= '2016-11-01' and date < '2016-12-01' limit 20
```
And it works. 
If you have some query using date in `Y-m-d` format and it does not work please can you open a new issue? So we can work on that. 

> Would be great if I can set a kind of env var something like GITQL_DEFAULT_LIMIT=100

I prefer to follow [*explicit is better than implicit*](https://www.python.org/dev/peps/pep-0020/) but your ideia is cool. Feel free if you want send a PR ;)

**Comment by vigo** [comment]
ok, it works but if I don't provide "limit XX" default resuts are always 10... Here is the [repo](https://github.com/vigo/dotfiles-universal) I make my tests. SQL is:

```sql
select author, message, date from commits where date >= '2016-01-01' and date < '2016-12-01'
```

I get 10 results unless I set limit XXX...

**Comment by cloudson** [comment]
Right @vigo, as this issue was about that question with dates, I'm closing it and created another about the [limit feature](#41)
