### ISSUE TITLE
Add a field in branches table with the remote(s)

### ISSUE THREAD

**Issue by elboletaire** [cloudson/gitql#35]
So we can filter branches i.e. `WHERE remote="origin"`.

An additional column to know if they are locale or just remote branches, plus another column for those which are currently merged would be awesome too.

**Comment by cloudson** [comment]
Hello @elboletaire 
I did not understand your issue. A branch can exists in many remotes, from `git pull` the branch itself has no relationship with that remote address. Can you give me some examples what you imagined?

**Comment by elboletaire** [comment]
For example, how could you do something like this:

~~~bash
git branch --no-merged -r
~~~

...with gitql?

I'm sorry but I don't understand this part:

> A branch can exists in many remotes, from `git pull` the branch itself has no relationship with that remote address.

A branch can exist in many remotes, but it could not be. For example, something I regularly do is to add the `upstream` remote to my fork pointing to the original project (note, I always name `upstream` to an fork's original project while `origin` is always my project git repo; BTW, this is the default in git).

What I don't understand is what you're saying about `git pull`. If you do `git pull` it defaults to `git pull origin [BRANCH]` where `[BRANCH]` varies depending on what you've configured in your repo (remember that I can be working on a `wasfasasfs` branch which points to origin@master).

**Comment by cloudson** [comment]
Oh, I got it @elboletaire . It seems a nice improvement .
I hope to work on this as soon as possible but if you want to do this, feel free.

**Comment by cloudson** [comment]
As we didn't see many other users requesting this branch feature and I'm worried that we have some important hidden bugs to solve first, I'm closing this one and all the discussions can be moved to #18
