### ISSUE TITLE
Error when I use the plugin

### ISSUE THREAD

**Issue by piclemx** [cloudson/gitql#36]
dyld: Library not loaded: libgit2.21.dylib
  Referenced from: /usr/local/bin/gitql
  Reason: image not found
[1]    56160 abort      gitql "select message from commits"

I'm on Mac OSX

**Comment by cloudson** [comment]
Hi @piclemx . 
Did you exported the DYLD_LIBRARY_PATH environment variable ?

**Comment by piclemx** [comment]
Yes

**Comment by msankhala** [comment]
Actually that export variable DYLD_LIBRARY_PATH step should be mentioned before the `make` step under installation section in README.md. `make` for me failed at first attempt then i set that `DYLD_LIBRARY_PATH` variable then `make` step worked fine for me.

**Comment by cloudson** [comment]
@piclemx there are other thread trying to make the installation easily. 
Can you help us with a test? 
I did a [commit](https://github.com/cloudson/gitql/commit/0de04dc6a63053b7540fbc531eeaf0690c708f81) and you could follow the steps 

```shell
cd $GOPATH/src/github.com/cloudson/gitql/
cp libgit2/install/lib/lib*  /usr/local/lib
gitql 
```  
It solves your problem?

**Comment by luizperes** [comment]
It seems to be duplicated from https://github.com/cloudson/gitql/issues/30 @piclemx, take a look

**Comment by piclemx** [comment]
@cloudson Yes this is working 👍

**Comment by luizperes** [comment]
Sweet, @piclemx, could you close this issue? :)

**Comment by piclemx** [comment]
Done ;)
