### ISSUE TITLE
Add support to environment variable define the default limit

### ISSUE THREAD

**Issue by cloudson** [cloudson/gitql#41]
Based on #33 and to avoid always to write the limit word we could to have a environment variable that defines that
eg.:  `GITQL_DEFAULT_LIMIT`

**Comment by luizperes** [comment]
How about passing that on a flag as well?

**Comment by cloudson** [comment]
@luizperes for me there is no difference between use the query parameter or a flag.

**Comment by cloudson** [comment]
For me it's something that we can think better in the future, I'm leaving the idea to keep the issues more updated.
