### ISSUE TITLE
Better videos showing the tool

### ISSUE THREAD

**Issue by cloudson** [cloudson/gitql#45]
As gitql has changed, we need to improve the documentation with new videos showing the features. 
I love the asciinema tool and I've tried to create a [new one](https://asciinema.org/a/97094) there.
I thought to create specific short videos about 

* How to work with range dates 
* How to use the different output types
* How to use the `in` word or sorting lines
* How to search for other tables different than `commits`

**Comment by musiKk** [comment]
The "see more here" link in the README (https://asciinema.org/a/8863) also is a 404.
