### ISSUE TITLE
Error: git-ql died of signal 9

### ISSUE THREAD

**Issue by paritosh16** [cloudson/gitql#51]
Environment Details - 
* Operating System - MAC OS Sierra (10.12.4)
* Go version - go1.8
* cmake version - 3.8.0
* make version - GNU Make 3.81

I have installed `gitql` as mentioned in the README file.

Whenever I run `gitql`, I get the following error - 

    paritoshwalvekar in ~/go/src/github.com/cloudson/gitql on develop λ gitql
    [1]    10778 killed     gitql
    paritoshwalvekar in ~/go/src/github.com/cloudson/gitql on develop λ git ql
    error: git-ql died of signal 9

If I have missed something obvious, I would be glad to fix that.

**Comment by luizperes** [comment]
This doesn't seem to be an error with `git` rather than `gitql`.

Tale a look [here](http://stackoverflow.com/questions/7985124/git-push-error-index-pack-died-of-signal-9)

**Comment by luizperes** [comment]
Hi @paritosh16, did you fix it?

**Comment by cloudson** [comment]
I'm closing this, if the problem still hapenning, please, let us know @paritosh16 .
