### ISSUE TITLE
Adding the package to awesome-go. 

### ISSUE THREAD

**Issue by abhi18av** [cloudson/gitql#53]
Hi guys, I think this a a wonderful piece of work and I wanted to add it to the awesome-go list, but it's running into trouble with the CI. 

Could you help me out?

**Comment by luizperes** [comment]
Yeah, could you give me details?

**Comment by luizperes** [comment]
Hi @abhi18av, did you get it? (Can I close this issue?)

**Comment by abhi18av** [comment]
Well, not yet.

I became rely busy with other things here but I'll give it another try soon. 

I'll close the issue though ;)
