### ISSUE TITLE
Error while make tasks 

### ISSUE THREAD

**Issue by abhi18av** [cloudson/gitql#54]
Hi @cloudson 

I was trying to install this on my system but it throws the following error 

```sh
make[1]: Leaving directory '/home/eklavya/go/src/github.com/cloudson/gitql/libgit2'
Building...
# github.com/cloudson/git2go
../git2go/blob.go:4:18: fatal error: git2.h: No such file or directory
compilation terminated.
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 2

```

Could you help me out here ?

**Comment by luizperes** [comment]
Hi @abhi18av, please check https://github.com/cloudson/gitql/issues/30 and https://github.com/cloudson/gitql/issues/48 and reply me back if you have any problems! Cheers

**Comment by abhi18av** [comment]
Yup, worked like magic. Thanks @luizperes  :+1:
