### ISSUE TITLE
Parse error don't include newline at the end

### ISSUE THREAD

**Issue by jcubic** [cloudson/gitql#57]
If you make error in sql you get error and there are no new line at the end so it mess up command line in bash, you need to press enter and then up arrow to edit the command.

**Comment by jsixface** [comment]
I've fixed this error in my last PR.
Can you validate this with the latest code.

On Oct 22, 2017 3:27 AM, Jakub Jankiewicz <notifications@github.com> wrote:

If you make error in sql you get error and there are no new line at the end so it mess up command line in bash, you need to press enter and then up arrow to edit the command.

**Comment by luizperes** [comment]
Can you check that please @jcubic ? :)

**Comment by jcubic** [comment]
Yes, it's fixed thanks.
