### ISSUE TITLE
like or regex search

### ISSUE THREAD

**Issue by jcubic** [cloudson/gitql#59]
It would be nice to have like or regex keywords to search commits by part of the message like this:
```sql
select message from commits where message like "%console.log%"
```

to have all commits that have console.log in it or when count(*) is added 

```sql
select count(*) from commits where message like "%console.log%"
```

**Comment by luizperes** [comment]
that would be great to have, it is in `TODO` now :)

**Comment by jsixface** [comment]
Implementing a where clause `like` and grouping mechanisms like `count(*)` should be in different issues.

**Comment by jcubic** [comment]
There is already an issue for `count(*)` #26

**Comment by cloudson** [comment]
It's done by @jsixface  :)
