### ISSUE TITLE
move to an organization account

### ISSUE THREAD

**Issue by DanielRuf** [cloudson/gitql#67]

**Comment by cloudson** [comment]
I can't see any big advantage creating an organization. I mean, if we have some ideas in how to break the code in different packages or create new products based on it, it make sense. 
What is your goals @DanielRuf ?

**Comment by DanielRuf** [comment]
The main advantage is more granular control, teams with different rights, collaborators and contributors, higher truck factor and no dependence on a personal account.

**Comment by cloudson** [comment]
Got it. As currently we don't have too many contributors and the number of maintainers is low, I think that we don't need that kind of control yet. But I really would like to work more to release a version 2 of Gitql and I will consider your suggestions in the future. Thanks a lot for that.
