### ISSUE TITLE
feature request:publish windows build binary

### ISSUE THREAD

**Issue by pedoc** [cloudson/gitql#78]
RT

**Comment by cloudson** [comment]
Hey @pedoc , for now we don't publish an executable binary because gitql has a dynamic dependency . Maybe the best solution would be change that to a static one. If you have some suggestion in how to solve that problem I would appreciate that.

**Comment by pedoc** [comment]
hi,thanks u reply.
another option is that if the project can be successfully compiled in msys2 or cygwin (etc.), it is also feasible, but I have tried it, unfortunately, not working.

i am happy to help solve the compilation problem, but I am lacking enough go-lang experience, i am C#er

**Comment by cloudson** [comment]
Hey @pedoc, thank you for your availablity. Can restart all the installation process? 
@budden is helping us with windows support and maybe he can help you if it still not working here #79. 
We created a new release right now and base on it I will close this proposal.
